"""create_all

Revision ID: a53ea992d4ac
Revises: 07c71f4389b6
Create Date: 2023-05-27 10:59:25.882704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a53ea992d4ac"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("surname", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("patronymic", sa.String(length=128), nullable=False),
        sa.Column("position", sa.String(length=128), nullable=False),
        sa.Column("division", sa.String(length=128), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "child_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("employee_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gift_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("child_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("distribution_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gift_model")
    op.drop_table("child_model")
    op.drop_table("employee_model")
    # ### end Alembic commands ###
